Thrifty/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Diagnostics;
using Thrifty.Models;
using Thrifty.Services.ItemCategory;

namespace Thrifty.Controllers
{
    public class HomeController : Controller
    {

        private readonly IItemCategoryService _itemCategoryService;
        public HomeController(IItemCategoryService itemCategoryService)
        {
            _itemCategoryService = itemCategoryService;
        }


        public async Task<IActionResult> Index()
        {
            var item = await _itemCategoryService.GetAllInStock();
            return View(item);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
        





        //private string ConvertViewToString(string viewName, object model)
        //{
        //    try
        //    {
        //        ViewData.Model = model;
        //        using (StringWriter writer = new StringWriter())
        //        {
        //            var httpContext = new DefaultHttpContext { RequestServices = this.HttpContext.RequestServices };
        //            var actionContext = new ActionContext(httpContext, this.ControllerContext.RouteData, this.ControllerContext.ActionDescriptor);

        //            var viewResult = _viewEngine.FindView(actionContext, viewName, false);
        //            var viewContext = new ViewContext(actionContext, viewResult.View, ViewData, null , writer, new HtmlHelperOptions());

        //            viewResult.View.RenderAsync(viewContext).GetAwaiter().GetResult();

        //            return writer.ToString();
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        throw;
        //    }
        //}



    }
}

Thrifty/Controllers/HomeItemController.cs
using Microsoft.AspNetCore.Mvc;
using Thrifty.Services.Item;

namespace Thrifty.Controllers
{
    public class HomeItemController : Controller
    {

        private readonly IItemService _itemService;
        public HomeItemController(IItemService itemService)
        {
            _itemService = itemService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            var item = await _itemService.GetWithImages(id);
            return View(item);
        }
    }
}

Thrifty/Views/Home/Index.cshtml
@using Thrifty.Models
@model List<ItemCategory>

@{
    ViewData["Title"] = "Home Page";
}


<style>
    .btn-More-Detils {
        display: flex;
        align-items: center;
        padding-inline: 15px;
        padding-block: 5px;
        background-color: var(--bg-color);
        color: var(--title-color);
        border:none;
    }

        .btn-More-Detils i {
            padding-inline-start:10px;
        }

    .new__data{
        width:100%;
    }
    
    .d-flex{
        display:flex !important;
    }

    .align-items-center{
        align-items:center;
    }

    .justify-content-between{
        justify-content:space-between;
    }


    .modal{
        position:absolute;
        left: 0;
        right:0;
        top:0;
        bottom:0;
        background-color: #000000a6;
        display:flex;
        margin:auto;
        z-index:10000000;
    }

    .modal-conten{
        max-width:300px;
        height : 70vh;
        background-color: var(--bg-color);
    }
  
</style>

<main class="main">
    <section class="home section" id="home">
        <div class="home__container container grid">
            <div class="home__data">
                <h1 class="home__title">
                    Thrifty Clothing <br>
                    Collection
                </h1>
                <a href="#new" class="button__link">
                    EXPLORE <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="home__images">
                <img src="Img/Home_2.jpg" alt="home image">
                <img src="Img/Home_1.jpg" alt="home image">
            </div>
        </div>
    </section>
    @if (Model != null && Model.Count() > 0)
    {
        foreach (var cat in Model)
        {
            if (cat.Items.Count() > 0)
            {
                <section class="new section" id="new">
                    <h2 class="section__title">
                        @cat.name
                    </h2>
                    <div class="new__container container grid">
                        @foreach (var item in cat.Items)
                        {
                            <article class="new__card">
                                @if(item.mainImage != null)
                                {
                                    <img src="data:image/png;base64,@item.mainImage.imageBase" alt="new image" class="new__img">
                                }
                                <form id="itemMoreDetils" class="new__link" method="post" action="/Home/GetModal">
                                    <div class="new__data">
                                        <h2 class="new__title">
                                            @item.name
                                        </h2>
                                        <p>
                                            Price : @item.price JOD
                                        </p>
                                        <P class="d-flex align-items-center justify-content-between">
                                            Size : @item.size
                                            <a type="submit" asp-action="Index" asp-controller="HomeItem" asp-route-id="@item.id" class="btn-More-Detils">
                                                More Detils
                                                <i class="ri-arrow-right-line"></i>
                                            </a>
                                        </P>
                                    </div>
                                </form>
                            </article>
                        }
                    </div>
                </section>
            }
        }
    }
</main>



@Html.Partial("_LayoutFooter")